## Workshop Plan

| Time | Content |
|------|---------|
| 13:00 to 13:20 | Introduction <br> Fill in [Pre Workshop Surveys](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=_oivH5ipW0yTySEKEdmlwuNcJ7ofdGhDpRexUha3NYhUMU5QQ000NVpFTVRKRTEzRDRCQ0w4V05XMS4u){target="_blank"} <br> Check Pre-Requisites |
| 13:20 to 13:40 | Talk Through of Plugin Architecture <br> What to Consider When Translating Code.|
| 13:40 to 14:50 | Interactively translate Stata packages to other languages. (Different packages, same workflow)|

## Workshop Times
| Time | Content |
|------|---------|
| 14:50 to 15:10 | 🍰 Break 🍰 |
| 15:00 | Fire Alarm Test | 

## Workshop Times
| Time | Content |
|------|---------|
| 15:10 to 16:30 | Run translated Code <br> Compare different translations. <br> Assess code translation for post workshop survey. |
| 16:30 to 17:00 | Wrap-up <br> Discussion <br> Fill in [post work shop surveys](https://forms.office.com/Pages/ResponsePage.aspx?id=_oivH5ipW0yTySEKEdmlwkgtFALcEfRKnhSRePBd-9dUQjI1SzdIT1pROVBHVDJSNDU3QUNZVTBGTiQlQCN0PWcu){target="_blank"}. |

## Introduction - [Prerequisites](https://github.com/stata-translations/Stata2R/blob/main/docs/workshop.md#essential){target="_blank"}

 - Claude Code (CLI or Desktop App)
 - Stata
 - R
 - git + github account

## Introduction - Time for Survey

5 minutes to Fill in [Pre Workshop Surveys](https://forms.cloud.microsoft/Pages/ResponsePage.aspx?id=_oivH5ipW0yTySEKEdmlwuNcJ7ofdGhDpRexUha3NYhUMU5QQ000NVpFTVRKRTEzRDRCQ0w4V05XMS4u){target="_blank"}

## Introduction - Claude

[Demo of Claude Code CLI and App.](https://github.com/stata-translations/Stata2R/blob/main/docs/workshop.md#setup-and-installation)


## What's in a plugin
A plugin is a collection of `Skills`

[Plugin Source](https://github.com/stata-translations/Stata2R){target="_blank"}


```md
└── skills
    ├── add-missing-tests
    │   └── SKILL.md
    ├── add-stata-tests-r
    │   └── SKILL.md
    ├── hello
    │   └── SKILL.md
    ├── pseudocode-to-r
    │   ├── assets
    │   ├── references
    │   │   └── language_mappings.md
    │   └── SKILL.md
    ├── run-stata
    │   └── SKILL.md
    ├── stata-to-pseudocode
    │   ├── assets
    │   ├── references
    │   └── SKILL.md
    └── translation-strategy
        ├── assets
        ├── references
        └── SKILL.md

15 directories, 8 files
```

## What's in a Skill
Plain text:
[Plugin Source](https://github.com/stata-translations/Stata2R/blob/main/stata-translation/skills/hello/SKILL.md)

## Pause for questions before we start with translation.

 - Has everyone got a Stata package to work on?
 - Any other questions. 

## Start of interactive Translation Session.

Run through [workshop](https://github.com/stata-translations/Stata2R/blob/main/docs/workshop.md#determine-the-code-translation-strategy){target="_blank"}

Break at 14:50

## Code review and Interactive Running.

We have around 80 minutes to assess the translated code.

 - Can you run the translated code and get equivalent results to Stata?
 - How does your translation compare to other peoples?
 - Work through the questions in the [post work shop survey](https://forms.office.com/Pages/ResponsePage.aspx?id=_oivH5ipW0yTySEKEdmlwkgtFALcEfRKnhSRePBd-9dUQjI1SzdIT1pROVBHVDJSNDU3QUNZVTBGTiQlQCN0PWcu){target="_blank"}. (If you assessed more than one package you can submit multiple results).
 
## Wrap up and Discussion.

 - Any general questions. 
 - Fill in the [post work shop survey](https://forms.office.com/Pages/ResponsePage.aspx?id=_oivH5ipW0yTySEKEdmlwkgtFALcEfRKnhSRePBd-9dUQjI1SzdIT1pROVBHVDJSNDU3QUNZVTBGTiQlQCN0PWcu){target="_blank"} before leaving if you haven't already done so.
